config/routes.rb
Qrrl::Application.routes.draw do
  

  resources :badges

  resources :answers

  resources :questions

  devise_for :users
  resources :users, :only => :show

  root :to => "home#index"
  
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  # include Mongoid::Slug
  include Mongoid::Timestamps
  belongs_to :user
  belongs_to :question
end

app/models/badge.rb
class Badge
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps
  belongs_to :user
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps
  belongs_to :user
  has_many :answers

  field :title
  field :type
  field :body
  field :tags,     type: Array
  field :choices,  type: Array
  field :location, type: Array
  field :private,  type: Boolean, default: false
  field :likes,    type: Integer, default: 0
  field :likers,   type: Array

  validates_presence_of :title, :type, :private, :likes
  slug :title, :history => true


  private

  def self.sanitize_params(question)
    question[:choices] = question[:choices].values
    question[:tags] = question[:tags].split(",")
    if question[:private] == "0"
      question[:private] = 0
    else
      question[:private] = 1
    end
    return question
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Slug

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time
  ## Rememberable
  field :remember_created_at, :type => Time
  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  ## Encryptable
  # field :password_salt, :type => String
  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable
  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
  ## Token authenticatable
  # field :authentication_token, :type => String
  field :name
  field :bio,     :type => String
  field :level,   :type => Integer
  field :love,    :type => Integer
  field :q_count, :type => Integer
  field :a_count, :type => Integer
  slug  :name 
  has_many :questions
  has_many :answers
  has_many :badges


  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @users = User.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = current_user.questions
  end
  
  def show
    @question = Question.find_by_slug(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find_by_slug(params[:id])
  end
  
  def create
    Question.sanitize_params(params[:question])
    @question = current_user.questions.create(params[:question])
    if @question.save
      redirect_to @question, notice: "Question has been asked!"
    else
      params[:question][:tags] = params[:question][:tags].to_s.gsub(/[^\w\.,@-]/,"")
      binding.pry
      render action: "new"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Qrrl
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body{:class => params[:controller]}
    #container.container
      %header
        %nav
          %ul.hmenu
            = render 'shared/navigation'
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
      #main{:role => "main"}
        = yield
      %footer

app/views/questions/_form.html.haml
= form_for @question do |f|
  -if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label      :title
    = f.text_field :title
  .field
    = f.label      :type
    = f.select     :type, ["Poll", "Short", "Rant"]
  .field.short{ style: 'display:none;'}
    = f.label      :body
    = f.text_field :body
  .field.long{  style: 'display:none;'}
    = f.label      :body
    = f.text_area  :body, rows: 5
  .field.choices
    = f.label      :choices
    = f.fields_for :choices do |choice|
      .field.options
        %p
          = choice.label "Opt 1"
          = choice.text_field :'0', placeholder: "Yes", class: "question-choice-option"
        %p
          = choice.label "Opt 2"
          = choice.text_field :q1, placeholder: "No",  class: "question-choice-option"
    = link_to " Add","javascript:void(0)", class: "icon-plus-sign add-choice"
  .field
    = f.label      :tags
    = f.text_field :tags
  .field
    = f.label      :private
    = f.check_box  :private
  .actions
    = f.submit 'Ask', class: 'btn'

app/views/questions/edit.html.haml
= render 'form'

app/views/questions/index.html.haml
%h1 My Questions
%p= "All #{number_to_human(@questions.count)} of them"
%p= link_to "new question", new_question_path
- @questions.each do |question|
  %p
    question.title

app/views/questions/new.html.haml
%h1 New Question
= render 'form'
= link_to 'Back', questions_path

app/views/questions/show.html.haml
#question
  %h2= "#{@question.title}?"
  - if @question.type == "Poll"
    - @question.choices.each do |opt|
      %p= opt
  - else
    = @question.body
  

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li
    = link_to('Logout', destroy_user_session_path, :method=>'delete')
- else
  %li
    = link_to('Login', new_user_session_path)
- if user_signed_in?
  %li
    = link_to('Edit account', edit_user_registration_path)
- else
  %li
    = link_to('Sign up', new_user_registration_path)

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}